CREATE TABLE address (
    id BIGINT(255) NOT NULL UNIQUE AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    complement VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    locale VARCHAR(255) NOT NULL,
    uf VARCHAR(255) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);





